/* Sharing Thoughts */

CREATE TABLE `sharedthought` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL,
  `unit_id` bigint(20) NOT NULL,
  `positive_negative` int(11) NOT NULL,
  `is_patient` tinyint(1) DEFAULT '0',
  `is_principal_carer` tinyint(1) DEFAULT '0',
  `is_relative` tinyint(1) DEFAULT '0',
  `is_friend` tinyint(1) DEFAULT '0',
  `is_about_me` tinyint(1) DEFAULT '0',
  `is_about_other` tinyint(1) DEFAULT '0',
  `is_anonymous` tinyint(1) DEFAULT '0',
  `start_date` datetime DEFAULT NULL,
  `end_date` datetime DEFAULT NULL,
  `is_ongoing` tinyint(1) DEFAULT '0',
  `location` text,
  `description` text,
  `suggested_action` text,
  `concern_reason` text,
  `likelihood_recurrence` int(11) NOT NULL,
  `how_serious` int(11) NOT NULL,
  `is_submitted` tinyint(1) DEFAULT '0',
  `date_last_saved` datetime DEFAULT NULL,
  `allocation_user_id` bigint(20) NOT NULL,
  `is_action_taken` tinyint(1) DEFAULT '0',
  `filterer_user_id` bigint(20) NOT NULL,
  `is_patient_contacted` tinyint(1) DEFAULT '0',
  `notes` text,
  `status` text,
  `is_viewed` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
